### ISSUE TITLE
micro api作为网关是不是功能上弱了点？

### ISSUE THREAD

**Issue by curry7313** [qin-jd/shopping#3]
Hi,最近我也在学习micro，对于API网关这块，官方给的资料好少，access_log如何记录呢？包括一般网关具备的限流、认证等功能似乎micro api都没有提到。有什么想法呢？

**Comment by qin-jd** [comment]
@curry7313  micro api 也是利用go-micro开发的一个微服务，该服务监听了8080端口，同样具有go-micro作为微服务基本的功能，比如服务注册与发现。他的本质是一个路由器，基于go-api，基于路由规则，把request路由到对应的微服务上去。

如你所示，限流、认证、日志记录功能，micro api确实没有提供这些。但是go-micro有强大的wrapper（中间件机制），基于中间件可以集成诸如限流，认证，或者日志记录等功能。官方的插件里就有限流限速的中间件。https://github.com/micro/go-plugins/tree/master/wrapper/ratelimiter  。

我猜micro的作者可能是想要保持api网关的轻量，所以并没有给micro api增加更多别的功能。

如果你觉得功能弱了些可以采用世面上做的好的网关放在你的微服务的入口边缘，比如KONG这种。应该也很容易集成。

以上都是个人理解。有错误了可以指出。

**Comment by curry7313** [comment]
同意你的看法。顺便一问，如果用KONG作为API网关，如何集成到我们的系统中来呢，主要是如何和consul这种服务注册/发现的工具集成呢？我在KONG的官网上似乎没找到我想要的答案。

**Comment by curry7313** [comment]
> @curry7313 micro api 也是利用go-micro开发的一个微服务，该服务监听了8080端口，同样具有go-micro作为微服务基本的功能，比如服务注册与发现。他的本质是一个路由器，基于go-api，基于路由规则，把request路由到对应的微服务上去。
> 
> 如你所示，限流、认证、日志记录功能，micro api确实没有提供这些。但是go-micro有强大的wrapper（中间件机制），基于中间件可以集成诸如限流，认证，或者日志记录等功能。官方的插件里就有限流限速的中间件。https://github.com/micro/go-plugins/tree/master/wrapper/ratelimiter 。
> 
> 我猜micro的作者可能是想要保持api网关的轻量，所以并没有给micro api增加更多别的功能。
> 
> 如果你觉得功能弱了些可以采用世面上做的好的网关放在你的微服务的入口边缘，比如KONG这种。应该也很容易集成。
> 
> 以上都是个人理解。有错误了可以指出。

同意你的看法。顺便一问，如果用KONG作为API网关，如何集成到我们的系统中来呢，主要是如何和consul这种服务注册/发现的工具集成呢？我在KONG的官网上似乎没找到我想要的答案。

**Comment by qin-jd** [comment]
@curry7313  这个我也没有可落地的实验过，等有时间了我看看。目前只能是不停地找资料了
