### ISSUE TITLE
关于前端

### ISSUE THREAD

**Issue by codlin** [qin-jd/shopping#4]
请问前端准备使用什么技术？ 如果是采用SPA等SEO不友好呀

**Comment by qin-jd** [comment]
可以考虑使用SSR做服务端渲染

**Comment by codlin** [comment]
请问具体如何做呢？针对搜索引擎的爬虫导流到类似于phantomjs？ 
go-micro返回html而不是json这种案例有没有？
谢谢

**Comment by qin-jd** [comment]
如果你前端是用vue这种做的单页面应用的话，还要考虑SEO，其实就是把你的vue代码在服务端的node环境下提前渲染，生成带有数据的HTML字符串返回给浏览器，在这里go-micro只是后端服务数据提供者。渲染是node环境做的，这就是SSR服务端渲染。  
如果你没有使用vue这种单页面应用，你可以在go-micro微服务的最前端套一个PHP服务来处理页面渲染，当然PHP服务会有服务器性能损耗，你也可以找go的一些web框架轮子来做。这些web轮子调go-micro的数据。
无论哪种，我都倾向于后端隐藏的微服务只处理数据，页面的渲染单独交给不同的端去做。

**Comment by codlin** [comment]
明白了，非常感谢！
